name: PHPUnit (Symfony + Api Platform)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "PHP ${{ matrix.php }} + Symfony ${{ matrix.symfony }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']
        symfony: ['5.0.*', '5.1.*', '5.2.*', '5.3.*', '5.4.*', '6.0.*']
        xdebug: [ xdebug2 ]
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          # this is the only place we have to use PHP to avoid the lock to bash scripting
          php-version: ${{matrix.php}}
          coverage: ${{matrix.xdebug}}

      - name: Display versions
        run: |
          php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
          php -i
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-sf-${{ matrix.symfony }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-sf-${{ matrix.symfony }}-

      - name: Require Symfony version
        run: |
          composer global require --no-interaction --no-progress symfony/flex:^1.11
          composer config extra.symfony.require ${{ matrix.symfony }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install

      - name: Run test suite
        run: vendor/bin/simple-phpunit -v --coverage-text

