name: RuleEngine Bundle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.4', '8.0']
        symfony: ['4.4.*', '5.1.*', '5.2.*', '5.3.*']

    steps:
      - uses: actions/checkout@v2

      - name: Display versions
        run: |
          php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
          php -i
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-sf-${{ matrix.symfony }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-sf-${{ matrix.symfony }}-

      - name: Require Symfony version
        run: |
          composer global require --no-interaction --no-progress symfony/flex:^1.11
          composer config extra.symfony.require ${{ matrix.symfony }}

      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install

      - name: Run test suite
        run: vendor/bin/simple-phpunit -v
